version: '3.8'
services:
  angular-app:
    build:
      context: ./fms-adm
    ports:
      - "4200:4200"
    volumes:
      - ./fms-adm:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true # Força a atualização ao modificar arquivos
      - WATCHPACK_POLLING=true